/// <summary>
/// 보상과 비용 계산에 공통으로 사용하는 재화 종류. <para/>
/// 작업 UI에서 오름차순으로 정렬되기 때문에 등급이 높은 아이템일 수록 높은 번호를 부여할 것
/// </summary>
public enum RewardCurrencyType
{
    Coin = 0,
    Stone = 1,
    Bone = 2,
    Wood = 3,
    VodkaBottle = 4,
    WineBottle = 5,
    Molotov = 6,
    Lighter = 7,
    Carbon = 8,
    CameraNoLens = 9,
    Lead = 10,
    Silver = 11,
    Iron = 12,
    IronPiece = 13,
    Aluminium = 14,
    Cement = 15,
    GunPowder = 16,
    Grenade = 17,
    FlareGrenade = 18,
    PistolBullet = 19,
    BigPistolBullet = 20,
    Matches = 21,
    Banana = 22,
    Drink = 23,
    Cookie = 24,
    SuitCase = 25,
    Backpack = 26,
    OpnedCan = 27,
    Trumpet = 28,
    Canabis = 29,
    TableTennisBat = 30,
    TennisBall = 31,
    Medkit = 32,
    RecordLP = 33,
    GasCan = 34,
    MetalLighter = 35,
    Cigar = 36,
    Book = 37,
    CarbonFiber = 38,
    SteelBeam = 39,
    SteelRod = 40,
    MachinePart = 41,
    Bolt = 42,
    Nail = 43,
    WireCutter = 44,
    Hammer = 45,
    Wrench = 46,
    Hydrogen = 47,
    Oxygen = 48,
    SilverKey = 49,
    Scandium = 50,
    Chlorine = 51,
    Silicon = 52,
    ToolBox = 53,
    Water = 54,
    WalkieTalkie = 55,
    FlashLight = 56,
    Keyboard = 57,
    FirePart = 200,
    SpecialPart = 201
}
